name: Pack and publish nuget

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: NuGet/setup-nuget@v1.0.5
      - name: Set up GH nuget source
        run: dotnet nuget add source --username Raicuparta --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Raicuparta/index.json"
      - name: Pack nuget
        run: nuget pack package -OutputFileNamesWithoutVersion -OutputDirectory build
      - name: Publish nuget
        run: |
          dotnet nuget push "build/OuterWilds.GameLibs.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
