name: Pack and publish nuget

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: NuGet/setup-nuget@v1.0.5
      - name: Pack nuget
        run: nuget pack package -OutputFileNamesWithoutVersion -OutputDirectory build

      # Runs a set of commands using the runners shell
      - name: Publish nuget
        run: |
          dotnet nuget push "build/OuterWilds.GameLibs.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
