name: Pack and publish nuget

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: NuGet/setup-nuget@v1.0.5
      - name: Pack nuget
        run: nuget pack package -OutputFileNamesWithoutVersion -OutputDirectory build
      - name: Publish nuget
        run: |
          nuget push "build/OuterWilds.GameLibs.nupkg" -ApiKey ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
